#!/bin/sh

ROOTPASSWORD=$1
NCUSERNAME=$2
NCUSERPASSWORD=$3

mysql -u root -p$ROOTPASSWORD << EOF
CREATE DATABASE nextcloud;
CREATE USER '$NCUSERNAME'@'localhost' IDENTIFIED BY '$NCUSERPASSWORD';
GRANT ALL ON nextcloud.* TO '$NCUSERNAME'@'localhost';
FLUSH PRIVILEGES;
EOF

touch /var/db/mysql_secure/MYSQL_NEXTCLOUD_ADMIN_DONE
